import { useState, useEffect } from 'react'
import { FileText, Download, MessageSquare, Loader } from 'lucide-react'
import Layout from '@/components/Layout'
import { apiClient } from '@/api/client'
import { useAuthStore } from '@/store/authStore'
import toast from 'react-hot-toast'

interface Session {
  session_id: string
  created_at: string
  symptom_text: string
  red_flag: boolean
}

interface BriefSummary {
  patientName: string
  date: string
  conditions: string[]
  urgentAction: string | null
}

export default function BriefPage() {
  const { userId } = useAuthStore()
  const [sessions, setSessions] = useState<Session[]>([])
  const [selectedSession, setSelectedSession] = useState<string>('')
  const [generating, setGenerating] = useState(false)
  const [briefSummary, setBriefSummary] = useState<BriefSummary | null>(null)

  useEffect(() => {
    if (userId) {
      apiClient.get(`/symptoms/sessions?limit=10`)
        .then((res) => setSessions(res.data || []))
        .catch(() => {})
    }
  }, [userId])

  // Reset brief summary when session changes
  useEffect(() => {
    setBriefSummary(null)
  }, [selectedSession])

  const generate = async () => {
    if (!selectedSession) return toast.error('Select a symptom session first')
    setGenerating(true)
    try {
      // Step 1: Generate and download the PDF
      const res = await apiClient.post('/brief/generate', { session_id: selectedSession }, { responseType: 'blob' })
      const url = URL.createObjectURL(new Blob([res.data], { type: 'application/pdf' }))
      const a = document.createElement('a')
      a.href = url
      a.download = `praana_brief_${selectedSession.slice(0, 8)}.pdf`
      a.click()
      URL.revokeObjectURL(url)

      // Step 2: Fetch brief metadata for WhatsApp share text
      const session = sessions.find((s) => s.session_id === selectedSession)
      const sessionDate = session
        ? new Date(session.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })
        : new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })

      // Try to get brief data from the sessions endpoint for condition names
      let conditions: string[] = []
      if (session) {
        try {
          const sessionRes = await apiClient.get(`/symptoms/sessions?limit=20`)
          const sessions_data = sessionRes.data || []
          const matchedSession = sessions_data.find((s: any) => s.session_id === selectedSession)
          if (matchedSession?.ranked_conditions?.length > 0) {
            conditions = matchedSession.ranked_conditions
              .slice(0, 3)
              .map((c: any) => c.name || c.condition || '')
              .filter(Boolean)
          }
        } catch {
          // fallback gracefully
        }
      }

      setBriefSummary({
        patientName: 'Patient',
        date: sessionDate,
        conditions,
        urgentAction: session?.red_flag ? 'URGENT: Emergency flag was raised in this session.' : null,
      })

      toast.success('Doctor Brief downloaded!')
    } catch (err: any) {
      toast.error('Failed to generate brief. Please try again.')
    } finally {
      setGenerating(false)
    }
  }

  const shareWhatsApp = () => {
    if (!selectedSession) return toast.error('Generate a brief first')

    const session = sessions.find((s) => s.session_id === selectedSession)
    const sessionDate = session
      ? new Date(session.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })
      : new Date().toLocaleDateString('en-IN')

    let message = `*Praana Doctor Brief*\n`
    message += `Date: ${sessionDate}\n`

    if (briefSummary?.conditions?.length) {
      message += `\nAI shortlist (for discussion with doctor):\n`
      briefSummary.conditions.forEach((c, i) => {
        message += `${i + 1}. ${c}\n`
      })
    }

    if (session?.symptom_text) {
      const preview = session.symptom_text.slice(0, 120)
      message += `\nPresenting symptoms: ${preview}${session.symptom_text.length > 120 ? '...' : ''}\n`
    }

    if (briefSummary?.urgentAction) {
      message += `\n${briefSummary.urgentAction}\n`
    }

    message += `\n_Generated by Praana AI — all findings require clinical verification by a licensed physician._`
    message += `\n_Download the full PDF brief from Praana for your consultation._`

    window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, '_blank')
  }

  return (
    <Layout>
      <div className='max-w-2xl mx-auto px-4 py-8'>
        <div className='flex items-center gap-3 mb-6'>
          <FileText className='text-teal-400' size={24} />
          <h1 className='text-2xl font-bold text-white'>Doctor Brief</h1>
        </div>

        <div className='card mb-6'>
          <p className='text-slate-300 text-sm leading-relaxed mb-4'>
            A structured PDF your doctor reads in 90 seconds — patient identity, presenting symptoms in clinical language, AI differential shortlist, 30-day vitals summary, dietary flags, and suggested questions.
          </p>
          <div className='p-3 bg-teal-900/30 border border-teal-700/50 rounded-lg'>
            <p className='text-teal-300 text-xs'>The disclaimer "Generated by Praana AI to assist consultation — all findings require clinical verification" is locked and appears on every brief.</p>
          </div>
        </div>

        {/* Session selector */}
        <div className='card mb-4'>
          <label className='label'>Select symptom session</label>
          {sessions.length === 0 ? (
            <div className='text-center py-6'>
              <p className='text-slate-400 text-sm'>No symptom sessions yet.</p>
              <a href='/symptoms' className='text-teal-400 text-sm underline mt-1 block'>Run a symptom analysis first →</a>
            </div>
          ) : (
            <select
              value={selectedSession}
              onChange={(e) => setSelectedSession(e.target.value)}
              className='input'
            >
              <option value=''>Choose a session...</option>
              {sessions.map((s) => (
                <option key={s.session_id} value={s.session_id}>
                  {new Date(s.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })} — {s.symptom_text.slice(0, 50)}...
                  {s.red_flag ? ' 🚨' : ''}
                </option>
              ))}
            </select>
          )}
        </div>

        {/* Actions */}
        <div className='flex gap-3'>
          <button
            onClick={generate}
            disabled={generating || !selectedSession}
            className='btn-primary flex items-center gap-2 flex-1 justify-center'
          >
            {generating ? (
              <><Loader className='animate-spin' size={16} /> Generating PDF...</>
            ) : (
              <><Download size={16} /> Download PDF</>
            )}
          </button>
          <button
            onClick={shareWhatsApp}
            disabled={!selectedSession}
            title={briefSummary ? 'Share brief summary via WhatsApp' : 'Download PDF first to enable rich share'}
            className='flex items-center gap-2 bg-green-600 hover:bg-green-500 text-white font-semibold px-4 py-2.5 rounded-lg transition-colors disabled:opacity-50'
          >
            <MessageSquare size={16} />
            <span className='hidden sm:inline'>WhatsApp</span>
          </button>
        </div>

        {briefSummary && (
          <div className='mt-3 p-3 bg-green-900/20 border border-green-700/40 rounded-lg'>
            <p className='text-xs text-green-300'>
              Brief ready — WhatsApp share includes session date, AI shortlist preview, and symptoms summary.
            </p>
          </div>
        )}

        <p className='text-xs text-slate-500 text-center mt-6'>
          Praana compiles your profile, symptom session, last 30 days of vitals, and last 7 days of food logs into this brief.
        </p>
      </div>
    </Layout>
  )
}
