from datetime import datetime, timezone
from uuid import uuid4
from pydantic import BaseModel, ConfigDict, Field


class PatientCard(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True)
    name: str
    age: int | None
    gender: str
    blood_type: str | None
    bmi: float | None
    known_conditions: list[str]
    current_medications: list[str]
    allergies: list[str]
    city: str | None = None
    state: str | None = None


class VitalsSummaryItem(BaseModel):
    metric: str
    average: str
    trend: str
    flag: str | None = None


class DifferentialItem(BaseModel):
    condition: str
    icd_code: str
    one_line_reasoning: str


class BriefData(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True)
    patient_card: PatientCard
    presenting_symptoms_clinical: str
    ai_differential: list[DifferentialItem]
    vitals_summary: dict
    dietary_flags: list[str] = Field(default_factory=list)
    questions_for_doctor: list[str] = Field(default_factory=list)
    disclaimer: str = (
        'Generated by Praana AI to assist consultation — '
        'all findings require clinical verification by a licensed physician. '
        'This document does not constitute a medical diagnosis.'
    )


class BriefRecord(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True)
    brief_id: str = Field(default_factory=lambda: str(uuid4()))
    user_id: str
    session_id: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    brief_data: dict
    pdf_stored: bool = False


class BriefGenerateRequest(BaseModel):
    session_id: str
